### ISSUE TITLE
Błędny PIN

### ISSUE THREAD

**Issue by luke9642** [IrminaWalawska/IO5#23]
Błędny PIN podczas autoryzacji karty. Dopuszczone są 3 błędne próby. Po nich powinno wyskoczyć okno z wyborem płatności i komunikatem.

**Comment by rafalrp** [comment]
Jeden system akcjeptuje bledny PIN 3 razy, drugi dwa razy

**Comment by rafalrp** [comment]
Po przekroczeniu dopuszczalnej ilosci bledow, powrot do okna wyboru platnosci

**Comment by rafalrp** [comment]
8 jednostek
