### ISSUE TITLE
Błędne hasło przy logowaniu

### ISSUE THREAD

**Issue by luke9642** [IrminaWalawska/IO5#24]
Przy podaniu błędnego hasła pojawia się etykieta z komunikatem o błędzie. Dopuszczalne są 4 próby. Administrator ma prawo do zmiany hasła.

**Comment by rafalrp** [comment]
Dodanie kolumny do bazy danych "IS_BLOCKED", po 4 logowaniach kolumna przybiera wartosc True. Nie mozna logowac sie do konta gdy jest zablokowane.

**Comment by rafalrp** [comment]
13 jednostek
