### ISSUE TITLE
Czynnik ludzki i rozszerzalność

### ISSUE THREAD

**Issue by UMAI** [IrminaWalawska/IO5#4]
uzupełnienie dokumentacji związanej z czynnikami ludzkimi i rozszerzalnością

**Comment by DrzewoGevo** [comment]
Czynniki ludzkie:
- osoba niepełnosprawna, albo niedowidząca powinna umieć wykonać sprzedaż.
Rozszerzalność:
- możliwość wprowadzenia własnych metod płatności i zniżek.
- możliwość aktualizowania baz danych produktów.
- możliwość przeprowadzania lekkich zmian w interfejsie.
- możliwość instalowania aktualizacji.
